### ISSUE TITLE
gozillions causing stresstest to crash

### ISSUE THREAD

**Issue by elimisteve** [dwrensha/zillions#2]
That is, building https://github.com/elimisteve/gozillions/blob/master/gozillions.go then running `stresstest`, I get:

```
$ RUST_BACKTRACE=1 ./target/release/stresstest ~/django_projects/gozillions/gozillions --publishers 10 --messages 10 --subscribers 10 --repetitions 10 
running /home/steve/django_projects/gozillions/gozillions at address 127.0.0.1:8080
2017/03/12 04:57:08 Error listening on 127.0.0.1:127.0.0.1:8080: listen tcp: too many colons in address 127.0.0.1:127.0.0.1:8080
iteration 0 out of 10: launching 10 publishers, each sending 10 messages to 10 subscribers...
thread '<unnamed>' panicked at 'index 8 out of range for slice of length 1', /checkout/src/libcore/slice.rs:578
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: core::slice::slice_index_len_fail
             at /checkout/src/libcore/slice.rs:578
   1: <futures::future::join::Join<A, B> as futures::future::Future>::poll
   2: <futures::future::map::Map<A, F> as futures::future::Future>::poll
   3: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
   4: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
   5: std::panicking::try::do_call
   6: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
   7: <futures_cpupool::Sender<F, core::result::Result<<F as futures::future::Future>::Item, <F as futures::future::Future>::Error>> as futures::future::Future>::poll
   8: futures::task_impl::Run::run
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  11: <F as alloc::boxed::FnBox<A>>::call_box
  12: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:648
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  13: start_thread
  14: clone
```

I may be sending you back an invalid response?

**Comment by dwrensha** [comment]
If a server-under-test can cause the stress tester to crash, then that's definitely a bug in the stress tester!

**Comment by dwrensha** [comment]
Fixed by https://github.com/dwrensha/zillions/commit/d5742dea6fd5f133aba29d7ff82344f857a64423. Now gozillions causes the stresstest server to hang, which is still not ideal.
